### ISSUE TITLE
Fix-LineTo-Error Might Need Revert

### ISSUE THREAD

**Issue by matthewleffler1** [matthewleffler1/CollaborativeWhiteboardPython#14]
Merged Fix-LineTo-Error, but doesn't seem to work. Think we should revert to 2030849eca60b1bee4d009592857757f75182c08 if possible, which is the spider webbing branch

**Comment by kylebascomb** [comment]
Hmm, it works for me. Try making sure you pull from origin when you test on your system:

``git pull origin main``

If that doesn't work, try testing it in a new directory on your system. I'll do the same.

**Comment by kylebascomb** [comment]
I can confirm that it works for me. Run the following commands to new project to test.

```

mkdir new_whiteboard_testing
cd new_whiteboard_testing
git clone git@github.com:matthewleffler1/CollaborativeWhiteboardPython.git
cd CollaborativeWhiteboardPython
poetry install
poetry shell
flask run

```

**Comment by matthewleffler1** [comment]
Works now. Think I was having issues running poetry in a shell environment because of some administration issues within my Windows
